EducacionVirtual/Models/AcudientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EducaEnCasa.Models;
using EducacionVirtual.Data;

namespace EducacionVirtual.Models
{
    public class AcudientesController : Controller
    {
        private readonly EducacionVirtualContext _context;

        public AcudientesController(EducacionVirtualContext context)
        {
            _context = context;
        }

        // GET: Acudientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Acudientes.ToListAsync());
        }

        // GET: Acudientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var acudientes = await _context.Acudientes
                .FirstOrDefaultAsync(m => m.id == id);
            if (acudientes == null)
            {
                return NotFound();
            }

            return View(acudientes);
        }

        // GET: Acudientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Acudientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nombre,apellido,telefono,direccion")] Acudientes acudientes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(acudientes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(acudientes);
        }

        // GET: Acudientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var acudientes = await _context.Acudientes.FindAsync(id);
            if (acudientes == null)
            {
                return NotFound();
            }
            return View(acudientes);
        }

        // POST: Acudientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nombre,apellido,telefono,direccion")] Acudientes acudientes)
        {
            if (id != acudientes.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(acudientes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AcudientesExists(acudientes.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(acudientes);
        }

        // GET: Acudientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var acudientes = await _context.Acudientes
                .FirstOrDefaultAsync(m => m.id == id);
            if (acudientes == null)
            {
                return NotFound();
            }

            return View(acudientes);
        }

        // POST: Acudientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var acudientes = await _context.Acudientes.FindAsync(id);
            _context.Acudientes.Remove(acudientes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AcudientesExists(int id)
        {
            return _context.Acudientes.Any(e => e.id == id);
        }
    }
}

EducacionVirtual/Models/DocentesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EducaEnCasa.Models;
using EducacionVirtual.Data;

namespace EducacionVirtual.Models
{
    public class DocentesController : Controller
    {
        private readonly EducacionVirtualContext _context;

        public DocentesController(EducacionVirtualContext context)
        {
            _context = context;
        }

        // GET: Docentes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Docentes.ToListAsync());
        }

        // GET: Docentes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var docentes = await _context.Docentes
                .FirstOrDefaultAsync(m => m.id == id);
            if (docentes == null)
            {
                return NotFound();
            }

            return View(docentes);
        }

        // GET: Docentes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Docentes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nombre,apellido,telefono,direccion,nivel_educativo")] Docentes docentes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(docentes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(docentes);
        }

        // GET: Docentes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var docentes = await _context.Docentes.FindAsync(id);
            if (docentes == null)
            {
                return NotFound();
            }
            return View(docentes);
        }

        // POST: Docentes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nombre,apellido,telefono,direccion,nivel_educativo")] Docentes docentes)
        {
            if (id != docentes.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(docentes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DocentesExists(docentes.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(docentes);
        }

        // GET: Docentes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var docentes = await _context.Docentes
                .FirstOrDefaultAsync(m => m.id == id);
            if (docentes == null)
            {
                return NotFound();
            }

            return View(docentes);
        }

        // POST: Docentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var docentes = await _context.Docentes.FindAsync(id);
            _context.Docentes.Remove(docentes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DocentesExists(int id)
        {
            return _context.Docentes.Any(e => e.id == id);
        }
    }
}

EducacionVirtual/Models/EstudiantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EducaEnCasa.Models;
using EducacionVirtual.Data;

namespace EducacionVirtual.Models
{
    public class EstudiantesController : Controller
    {
        private readonly EducacionVirtualContext _context;

        public EstudiantesController(EducacionVirtualContext context)
        {
            _context = context;
        }

        // GET: Estudiantes
        public async Task<IActionResult> Index()
        {
            var educacionVirtualContext = _context.Estudiantes.Include(e => e.Acudiente).Include(e => e.Docente);
            return View(await educacionVirtualContext.ToListAsync());
        }

        // GET: Estudiantes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiantes = await _context.Estudiantes
                .Include(e => e.Acudiente)
                .Include(e => e.Docente)
                .FirstOrDefaultAsync(m => m.id == id);
            if (estudiantes == null)
            {
                return NotFound();
            }

            return View(estudiantes);
        }

        // GET: Estudiantes/Create
        public IActionResult Create()
        {
            ViewData["AcudienteID"] = new SelectList(_context.Acudientes, "id", "NombreCompletoA");
            ViewData["DocenteID"] = new SelectList(_context.Docentes, "id", "NombreCompletoD");
            return View();
        }

        // POST: Estudiantes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nombre,apellido,telefono,direccion,tarjetaIdentidad,edad,grado,AcudienteID,DocenteID")] Estudiantes estudiantes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estudiantes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AcudienteID"] = new SelectList(_context.Acudientes, "id", "NombreCompletoA", estudiantes.AcudienteID);
            ViewData["DocenteID"] = new SelectList(_context.Docentes, "id", "NombreCompletoD", estudiantes.DocenteID);
            return View(estudiantes);
        }

        // GET: Estudiantes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiantes = await _context.Estudiantes.FindAsync(id);
            if (estudiantes == null)
            {
                return NotFound();
            }
            ViewData["AcudienteID"] = new SelectList(_context.Acudientes, "id", "NombreCompletoA", estudiantes.AcudienteID);
            ViewData["DocenteID"] = new SelectList(_context.Docentes, "id", "NombreCompletoD", estudiantes.DocenteID);
            return View(estudiantes);
        }

        // POST: Estudiantes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nombre,apellido,telefono,direccion,tarjetaIdentidad,edad,grado,AcudienteID,DocenteID")] Estudiantes estudiantes)
        {
            if (id != estudiantes.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estudiantes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstudiantesExists(estudiantes.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AcudienteID"] = new SelectList(_context.Acudientes, "id", "NombreCompletoA", estudiantes.AcudienteID);
            ViewData["DocenteID"] = new SelectList(_context.Docentes, "id", "NombreCompletoD", estudiantes.DocenteID);
            return View(estudiantes);
        }

        // GET: Estudiantes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiantes = await _context.Estudiantes
                .Include(e => e.Acudiente)
                .Include(e => e.Docente)
                .FirstOrDefaultAsync(m => m.id == id);
            if (estudiantes == null)
            {
                return NotFound();
            }

            return View(estudiantes);
        }

        // POST: Estudiantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var estudiantes = await _context.Estudiantes.FindAsync(id);
            _context.Estudiantes.Remove(estudiantes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstudiantesExists(int id)
        {
            return _context.Estudiantes.Any(e => e.id == id);
        }
    }
}

EducacionVirtual/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] EducacionVitual</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header  class="accordion-header">
        @if (User.Identity.IsAuthenticated)
        {
            <nav  class="navbar navbar-expand-lg navbar-dark bg-primary">
                <div class="container">

                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EducacionVitual</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <ul class="navbar-nav">


                            <li class="nav-item">
                                <button type="button" class="btn btn-warning">
                                    <a class="nav-link text-dark" style="text-decoration: none" asp-area="" asp-controller="Home" asp-action="Index">Inico</a>
                                </button>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <button type="button" class="btn btn-success">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Docentes" asp-action="Index">Docentes</a>
                                    </button>
                                </li>
                                <li class="nav-item">
                                    <button type="button" class="btn btn-success">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Acudientes" asp-action="Index">Acudientes</a>
                                    </button>
                                </li>
                                <li class="nav-item">
                                    <button type="button" class="btn btn-success">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Preguntas" asp-action="Index">Preguntas</a>
                                    </button>
                                </li>
                                <li class="nav-item">
                                    <button type="button" class="btn btn-success">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Estudiantes" asp-action="Index">Estudiantes</a>
                                    </button>
                                </li>

                                <li class="nav-item">
                                    <button type="button" class="btn btn-success">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Actividades" asp-action="Index">Actividades</a>
                                    </button>
                                </li>

                                <li class="nav-item">
                                    <button type="button" class="btn btn-success">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Notas" asp-action="Index">Notas</a>
                                    </button>
                                </li>

                                <li class="nav-item">
                                    <button type="button" class="btn btn-info">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" title="Manage">Hola: @User.Identity.Name!</a>
                                    </button>
                                </li>
                            }
                            else if (User.IsInRole("Driver"))
                            {
                                <li class="nav-item">
                                    <button type="button" class="btn btn-success">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Estudiantes" asp-action="Index">Estudiantes</a>
                                    </button>
                                </li>

                                <li class="nav-item">
                                    <button type="button" class="btn btn-success">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Actividades" asp-action="Index">Actividades</a>
                                    </button>
                                </li>

                                <li class="nav-item">
                                    <button type="button" class="btn btn-success">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Notas" asp-action="Index">Notas</a>
                                    </button>
                                </li>

                                <li class="nav-item">
                                    <button type="button" class="btn btn-info">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" title="Manage">Hola: @User.Identity.Name!</a>
                                    </button>
                                </li>
                            }
                            <li class="nav-item">
                                <form class="form-inline" asp-area="" asp-controller="Account" asp-action="Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button type="submit" class="btn btn-danger">Salir</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container">
            &copy; 2021 - EducacionVirtual - <a asp-area="" asp-controller="Home" asp-action="Privacy">Terminos y Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>